[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@pythnetwork/entropy-sdk-solidity/=node_modules/@pythnetwork/entropy-sdk-solidity/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
